let rec f a =
  match a with
    §\tikzmark{recursivePatternCriteriumStart}§<*stopping pattern*> ->§\tikzmark{recursivePatternCriteriumStop}§
      §\tikzmark{recursivePatternStopStart}§<*stopping step*>§\tikzmark{recursivePatternStopEnd}§
    | _ ->
      §\tikzmark{recursivePatternRecurseStart}§<*recursion step*>§\tikzmark{recursivePatternRecurseEnd}§
