#line 2 "fflat.yy.c"

#line 4 "fflat.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[316] =
    {   0,
        5,    5,   91,   90,    2,   90,    1,   90,   90,   21,
       22,   14,   14,   13,   19,   14,   11,   11,   90,   25,
       90,   89,   90,   24,   18,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,   89,    2,    1,    0,    9,    0,
        7,   15,   16,   23,   17,   12,   11,    0,    0,   11,
        0,    0,    0,   11,   20,    0,   89,    0,   89,   89,
       28,   89,   89,   89,   89,   35,   89,   89,   89,   89,
       89,   89,   89,   89,   50,   51,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   65,   89,   67,   89,   89,

       89,   89,   89,   89,   89,   77,   89,   89,   89,   89,
       89,   89,   89,   89,   89,   10,    9,    8,    0,   17,
        0,   12,   11,    0,   12,   11,   11,    0,    9,   89,
       27,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       89,   41,   89,   89,   89,   89,   46,   47,   89,   89,
       89,   89,   89,   57,   89,   89,   89,   89,   89,   63,
       89,   89,   89,   89,   89,   71,   89,   73,   89,   89,
       89,   89,   79,   89,   89,   82,   83,   89,   89,   89,
       89,   89,   10,    0,   17,    3,   12,   89,   89,   30,
       89,   89,   89,   89,   36,   89,   39,   40,   89,   89,

       89,   89,   89,   89,   89,   89,   89,   56,   89,   89,
       89,   89,   89,   64,   66,   89,   89,   89,   89,   89,
       89,   76,    6,   80,   89,   84,   85,   89,   87,   89,
        4,   89,   89,   31,   32,   89,   89,   89,   89,   89,
       89,   44,   89,   89,   89,   89,   89,   89,   58,   89,
       89,   89,   89,   89,   89,   89,   89,   89,   89,   89,
       86,   88,   89,   29,   89,   89,   89,   38,   89,   43,
       89,   89,   49,   89,   53,   89,   89,   59,   60,   89,
       89,   89,   89,   70,   72,   74,   75,   81,   89,   33,
       89,   89,   89,   45,   89,   52,   89,   89,   61,   89,

       89,   69,   26,   34,   37,   89,   48,   89,   55,   89,
       68,   42,   54,   62,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    1,    1,    1,    1,    6,    7,
        8,    9,   10,    1,   11,   12,   13,   14,   15,   16,
       16,   16,   16,   16,   16,   17,   17,    1,    1,   18,
       19,    1,    1,   20,   21,   22,   21,   21,   23,   21,
       24,   24,   25,   24,   24,   26,   24,   24,   27,   24,
       24,   24,   24,   24,   28,   24,   24,   29,   24,   24,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   24,   24,   43,   44,   45,
       46,   47,   24,   48,   49,   50,   51,   52,   53,   54,
       55,   56,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[57] =
    {   0,
        1,    2,    3,    1,    1,    4,    1,    1,    1,    1,
        1,    1,    1,    5,    5,    5,    5,    1,    1,    1,
        6,    6,    6,    7,    7,    7,    7,    7,    7,    1,
        1,    1,    7,    6,    6,    6,    6,    6,    6,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7
    } ;

static yyconst flex_int16_t yy_base[325] =
    {   0,
        0,    0,  447,  448,  448,  444,  441,   52,    0,  435,
      448,  435,  448,  448,  412,  428,   72,   36,  429,  448,
      434,    0,    0,  448,    0,   24,   26,  395,   24,   23,
       62,  394,   22,   38,   68,   40,   64,   69,  398,   43,
       83,   32,   46,   91,  393,  448,  430,  104,  411,  110,
      410,    0,  448,  448,  428,  128,    0,  122,  138,  448,
      142,  404,    0,   73,  448,  424,    0,  422,  378,  389,
      376,  375,  383,  388,   91,   94,  118,  384,  114,  377,
      374,  370,  372,  370,    0,  118,  359,  364,  363,  368,
      374,  360,  365,  355,  364,    0,  368,    0,  367,  362,

      368,  126,  362,  129,  363,    0,  114,  353,  363,  360,
      354,  354,  132,  345,  356,  448,  166,  448,  384,  390,
      389,  164,  158,  175,  179,  210,  178,  385,  384,  338,
        0,  349,  348,  343,  335,  349,  344,  343,  335,  340,
      340,    0,  339,  338,  326,  340,    0,  337,  337,  333,
      328,  331,  313,    0,  331,  331,  314,  330,  325,    0,
      319,  316,  312,  307,  315,    0,  306,    0,  306,  304,
      309,  315,    0,  314,  317,    0,    0,  313,  304,  305,
      306,  303,  170,  337,  342,  448,  448,  295,  294,    0,
      296,  291,  288,  298,    0,  149,    0,    0,  290,  288,

      297,  291,  283,  298,  283,  285,  281,    0,  287,  289,
      283,  290,  275,    0,    0,  275,  288,  279,  272,  277,
      278,    0,    0,    0,  248,    0,    0,  252,    0,  246,
      448,  242,  214,    0,    0,  220,  228,  226,  212,  207,
      211,    0,  212,  212,  210,  210,  213,  101,    0,  202,
      211,  205,  200,  204,  195,  208,  198,  206,  191,  190,
        0,    0,  203,    0,  187,  184,  183,    0,  189,    0,
      175,  182,    0,  172,    0,  187,  186,    0,    0,  181,
      183,  179,  177,    0,    0,    0,    0,    0,  164,    0,
      174,  161,  164,    0,  163,    0,  169,  157,    0,  162,

      144,    0,    0,    0,    0,   80,    0,   67,    0,   37,
        0,    0,    0,    0,  448,  265,  272,  274,  281,  288,
      295,  298,  304,  311
    } ;

static yyconst flex_int16_t yy_def[325] =
    {   0,
      315,    1,  315,  315,  315,  315,  315,  316,  317,  315,
      315,  315,  315,  315,  315,  315,  315,   17,  315,  315,
      315,  318,  319,  315,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  315,  315,  316,  315,  316,
      315,  320,  315,  315,  321,  315,   18,  315,  315,  315,
      315,  315,  322,  315,  315,  323,  318,  315,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  315,  316,  315,  315,  324,
      315,  315,  315,  315,  315,  315,  322,  323,  315,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  316,  315,  324,  315,  315,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      315,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,    0,  315,  315,  315,  315,  315,
      315,  315,  315,  315
    } ;

static yyconst flex_int16_t yy_nxt[505] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   18,   18,   19,   20,   21,
       22,   22,   22,   22,   22,   22,   22,   22,   22,    4,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       22,   33,   34,   35,   36,   37,   38,   39,   40,   41,
       42,   43,   44,   22,   45,   22,   49,  315,   69,   72,
       85,   75,  315,   73,  315,   77,   86,   78,   70,   76,
      315,   87,   71,   93,  314,   88,   79,   94,  109,  111,
      110,  315,   50,   56,  103,   57,   57,   57,   57,  315,
       95,  112,  104,   58,   59,   80,   60,   60,   61,   62,

       63,   89,   96,   81,  313,   90,   58,   82,   49,   59,
       97,   98,   83,   91,  117,   99,  100,   61,   92,  101,
       60,   60,   64,  105,  312,   63,   60,   60,  106,  136,
      107,  113,  114,  137,   50,  123,  123,  108,  138,  276,
       50,  122,  122,  122,  122,  277,  139,  124,  124,  143,
       59,  125,  125,  125,  125,  126,  126,  126,  150,  140,
      151,  166,  169,  144,  172,   59,  141,  152,  173,  179,
       49,  123,  123,  180,   49,  167,  170,  122,  122,  122,
      122,  311,   60,   60,  238,   62,   59,  183,  125,  125,
      125,  125,  125,  125,  125,  125,   50,  310,  239,  309,

       50,   59,   60,   60,  308,   62,   60,  307,   64,  306,
      305,  304,   60,  303,  302,  301,  300,  187,  299,  298,
      297,  296,  187,  126,  126,  126,   60,  295,   64,  294,
      293,  292,   60,  291,   60,   60,  290,   62,  289,  288,
      287,  286,  285,  284,  283,  282,  281,  280,  279,  278,
      275,  274,  273,  272,  271,  270,  269,  268,   60,  267,
       64,  266,  265,  264,   60,   48,   48,   48,   48,   48,
       48,   48,   51,   51,   51,  263,   51,   51,   51,   67,
       67,   68,  262,   68,   68,   68,   68,   68,  119,  261,
      119,  119,  119,  119,  119,  120,  260,  120,  120,  120,

      120,  120,  127,  127,  128,  128,  128,  128,  128,  128,
      128,  185,  185,  259,  185,  185,  185,  185,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  237,  236,  235,
      234,  233,  232,  315,  231,  230,  229,  228,  227,  226,
      225,  224,  223,  222,  221,  220,  219,  218,  217,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  198,  197,  196,
      195,  194,  193,  192,  191,  190,  189,  188,  128,  129,
      186,  186,  184,  182,  181,  178,  177,  176,  175,  174,

      171,  168,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  149,  148,  147,  146,  145,
      142,  135,  134,  133,  132,  131,  130,   51,  129,   60,
      121,  118,  116,   47,  115,  102,   84,   74,   66,   65,
       55,   54,   53,   52,   47,   46,  315,    3,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315
    } ;

static yyconst flex_int16_t yy_chk[505] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    8,   18,   26,   27,
       33,   29,   18,   27,   18,   30,   33,   30,   26,   29,
       18,   34,   26,   36,  310,   34,   30,   36,   42,   43,
       42,   18,    8,   17,   40,   17,   17,   17,   17,   18,
       36,   43,   40,   17,   17,   31,   17,   17,   17,   17,

       17,   35,   37,   31,  308,   35,   17,   31,   48,   17,
       37,   37,   31,   35,   50,   37,   38,   17,   35,   38,
       17,   64,   17,   41,  306,   17,   17,   64,   41,   75,
       41,   44,   44,   75,   48,   58,   58,   41,   76,  248,
       50,   56,   56,   56,   56,  248,   76,   59,   59,   79,
       56,   59,   59,   59,   59,   61,   61,   61,   86,   77,
       86,  102,  104,   79,  107,   56,   77,   86,  107,  113,
      117,  123,  123,  113,  183,  102,  104,  122,  122,  122,
      122,  301,  123,  123,  196,  123,  122,  117,  124,  124,
      124,  124,  125,  125,  125,  125,  117,  300,  196,  298,

      183,  122,  127,  127,  297,  127,  123,  295,  123,  293,
      292,  291,  123,  289,  283,  282,  281,  125,  280,  277,
      276,  274,  125,  126,  126,  126,  127,  272,  127,  271,
      269,  267,  127,  266,  126,  126,  265,  126,  263,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      247,  246,  245,  244,  243,  241,  240,  239,  126,  238,
      126,  237,  236,  233,  126,  316,  316,  316,  316,  316,
      316,  316,  317,  317,  317,  232,  317,  317,  317,  318,
      318,  319,  230,  319,  319,  319,  319,  319,  320,  228,
      320,  320,  320,  320,  320,  321,  225,  321,  321,  321,

      321,  321,  322,  322,  323,  323,  323,  323,  323,  323,
      323,  324,  324,  221,  324,  324,  324,  324,  220,  219,
      218,  217,  216,  213,  212,  211,  210,  209,  207,  206,
      205,  204,  203,  202,  201,  200,  199,  194,  193,  192,
      191,  189,  188,  185,  184,  182,  181,  180,  179,  178,
      175,  174,  172,  171,  170,  169,  167,  165,  164,  163,
      162,  161,  159,  158,  157,  156,  155,  153,  152,  151,
      150,  149,  148,  146,  145,  144,  143,  141,  140,  139,
      138,  137,  136,  135,  134,  133,  132,  130,  129,  128,
      121,  120,  119,  115,  114,  112,  111,  110,  109,  108,

      105,  103,  101,  100,   99,   97,   95,   94,   93,   92,
       91,   90,   89,   88,   87,   84,   83,   82,   81,   80,
       78,   74,   73,   72,   71,   70,   69,   68,   66,   62,
       55,   51,   49,   47,   45,   39,   32,   28,   21,   19,
       16,   15,   12,   10,    7,    6,    3,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,

      315,  315,  315,  315
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "fflat.l"
#line 2 "fflat.l"
#include <stdio.h>
#include "fflat.tab.h"
/* See http://www.lysator.liu.se/c/ANSI-C-grammar-l.html */
#line 674 "fflat.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 18 "fflat.l"

#line 858 "fflat.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 448 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "fflat.l"
/* ignore whitespace */;
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 20 "fflat.l"
printf("Lex:NEWLINE '\\n' \n"); return NEWLINE;
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 21 "fflat.l"
printf("Lex:COMMENT '%s' \n",yytext); return COMMENT;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "fflat.l"
printf("Lex:COMMENT '%s' \n",yytext); return COMMENT;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "fflat.l"
printf("Lex:UNIT '%s' \n",yytext); return UNIT;
	YY_BREAK
case 6:
#line 25 "fflat.l"
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 25 "fflat.l"
printf("Lex:CHAR '%s' \n",yytext); return CHAR;
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 26 "fflat.l"
printf("Lex:BYTE '%s' \n",yytext); return BYTE;
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 27 "fflat.l"
printf("Lex:STRING '%s' \n",yytext); return STRING; /* missing tripple quote-strings */
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 28 "fflat.l"
printf("Lex:BYTELIST '%s' \n",yytext); return BYTELIST;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "fflat.l"
printf("Lex:INT '%s' \n",yytext); return INT;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "fflat.l"
printf("Lex:FLOAT '%s' \n",yytext); return FLOAT;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "fflat.l"
printf("Lex:INFIXOP '%s' \n",yytext); return INFIXOP;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "fflat.l"
printf("Lex:PREFIXOP '%s' \n",yytext); return PREFIXOP;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "fflat.l"
printf("Lex:BLOCK_COMMENT_START '%s' \n",yytext); return BLOCK_COMMENT_START;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "fflat.l"
printf("Lex:BLOCK_COMMENT_END '%s' \n",yytext); return BLOCK_COMMENT_END;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "fflat.l"
printf("Lex:END_OF_LINE_COMMENT '%s' \n",yytext); return END_OF_LINE_COMMENT;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "fflat.l"
printf("Lex:UNDERSCORE '%s' \n",yytext); return UNDERSCORE;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "fflat.l"
printf("Lex:DOT '%s' \n",yytext); return DOT;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "fflat.l"
printf("Lex:ASSIGNOP '%s' \n",yytext); return ASSIGNOP;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "fflat.l"
printf("Lex:LEFTPARN '%s' \n",yytext); return LEFTPARN;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "fflat.l"
printf("Lex:RIGHTPARN '%s' \n",yytext); return RIGHTPARN;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "fflat.l"
printf("Lex:LEFTINDEXING '%s' \n",yytext); return LEFTINDEXING;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "fflat.l"
printf("Lex:RIGHTINDEXING '%s' \n",yytext); return RIGHTINDEXING;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "fflat.l"
printf("Lex:EQ '%s' \n",yytext); return EQ;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "fflat.l"
printf("Lex:ABSTRACT '%s' \n",yytext); return ABSTRACT;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "fflat.l"
printf("Lex:AND '%s' \n",yytext); return AND;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "fflat.l"
printf("Lex:AS '%s' \n",yytext); return AS;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "fflat.l"
printf("Lex:ASSERT '%s' \n",yytext); return ASSERT;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "fflat.l"
printf("Lex:BASE '%s' \n",yytext); return BASE;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "fflat.l"
printf("Lex:_BEGIN '%s' \n",yytext); return _BEGIN;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "fflat.l"
printf("Lex:CLASS '%s' \n",yytext); return CLASS;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "fflat.l"
printf("Lex:DEFAULT '%s' \n",yytext); return DEFAULT;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "fflat.l"
printf("Lex:DELEGATE '%s' \n",yytext); return DELEGATE;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "fflat.l"
printf("Lex:DO '%s' \n",yytext); return DO;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 54 "fflat.l"
printf("Lex:DONE '%s' \n",yytext); return DONE;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 55 "fflat.l"
printf("Lex:DOWNCAST '%s' \n",yytext); return DOWNCAST;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 56 "fflat.l"
printf("Lex:DOWNTO '%s' \n",yytext); return DOWNTO;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 57 "fflat.l"
printf("Lex:ELIF '%s' \n",yytext); return ELIF;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 58 "fflat.l"
printf("Lex:ELSE '%s' \n",yytext); return ELSE;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 59 "fflat.l"
printf("Lex:END '%s' \n",yytext); return END;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 60 "fflat.l"
printf("Lex:EXCEPTION '%s' \n",yytext); return EXCEPTION;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 61 "fflat.l"
printf("Lex:EXTERN '%s' \n",yytext); return EXTERN;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 62 "fflat.l"
printf("Lex:FALSE '%s' \n",yytext); return FALSE;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 63 "fflat.l"
printf("Lex:FINALLY '%s' \n",yytext); return FINALLY;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 64 "fflat.l"
printf("Lex:FOR '%s' \n",yytext); return FOR;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 65 "fflat.l"
printf("Lex:FUN '%s' \n",yytext); return FUN;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 66 "fflat.l"
printf("Lex:FUNCTION '%s' \n",yytext); return FUNCTION;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 67 "fflat.l"
printf("Lex:GLOBAL '%s' \n",yytext); return GLOBAL;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 68 "fflat.l"
printf("Lex:IF '%s' \n",yytext); return IF;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 69 "fflat.l"
printf("Lex:IN '%s' \n",yytext); return IN;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 70 "fflat.l"
printf("Lex:INHERIT '%s' \n",yytext); return INHERIT;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 71 "fflat.l"
printf("Lex:INLINE '%s' \n",yytext); return INLINE;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 72 "fflat.l"
printf("Lex:INTERFACE '%s' \n",yytext); return INTERFACE;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 73 "fflat.l"
printf("Lex:INTERNAL '%s' \n",yytext); return INTERNAL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 74 "fflat.l"
printf("Lex:LAZY '%s' \n",yytext); return LAZY;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 75 "fflat.l"
printf("Lex:LET '%s' \n",yytext); return LET;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 76 "fflat.l"
printf("Lex:MATCH '%s' \n",yytext); return MATCH;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 77 "fflat.l"
printf("Lex:MEMBER '%s' \n",yytext); return MEMBER;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 78 "fflat.l"
printf("Lex:MODULE '%s' \n",yytext); return MODULE;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 79 "fflat.l"
printf("Lex:MUTABLE '%s' \n",yytext); return MUTABLE;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 80 "fflat.l"
printf("Lex:NAMESPACE '%s' \n",yytext); return NAMESPACE;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 81 "fflat.l"
printf("Lex:NEW '%s' \n",yytext); return NEW;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 82 "fflat.l"
printf("Lex:_NULL '%s' \n",yytext); return _NULL;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 83 "fflat.l"
printf("Lex:OF '%s' \n",yytext); return OF;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 84 "fflat.l"
printf("Lex:OPEN '%s' \n",yytext); return OPEN;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 85 "fflat.l"
printf("Lex:OR '%s' \n",yytext); return OR;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 86 "fflat.l"
printf("Lex:OVERRIDE '%s' \n",yytext); return OVERRIDE;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 87 "fflat.l"
printf("Lex:PRIVATE '%s' \n",yytext); return PRIVATE;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 88 "fflat.l"
printf("Lex:PUBLIC '%s' \n",yytext); return PUBLIC;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 89 "fflat.l"
printf("Lex:REC '%s' \n",yytext); return REC;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 90 "fflat.l"
printf("Lex:RETURN '%s' \n",yytext); return RETURN;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 91 "fflat.l"
printf("Lex:SIG '%s' \n",yytext); return SIG;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 92 "fflat.l"
printf("Lex:STATIC '%s' \n",yytext); return STATIC;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 93 "fflat.l"
printf("Lex:STRUCT '%s' \n",yytext); return STRUCT;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 94 "fflat.l"
printf("Lex:THEN '%s' \n",yytext); return THEN;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 95 "fflat.l"
printf("Lex:TO '%s' \n",yytext); return TO;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 96 "fflat.l"
printf("Lex:TRUE '%s' \n",yytext); return TRUE;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 97 "fflat.l"
printf("Lex:TRY '%s' \n",yytext); return TRY;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 98 "fflat.l"
printf("Lex:TYPE '%s' \n",yytext); return TYPE;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 99 "fflat.l"
printf("Lex:UPCAST '%s' \n",yytext); return UPCAST;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 100 "fflat.l"
printf("Lex:USE '%s' \n",yytext); return USE;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 101 "fflat.l"
printf("Lex:VAL '%s' \n",yytext); return VAL;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 102 "fflat.l"
printf("Lex:VOID '%s' \n",yytext); return VOID;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 103 "fflat.l"
printf("Lex:WHEN '%s' \n",yytext); return WHEN;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 104 "fflat.l"
printf("Lex:WHILE '%s' \n",yytext); return WHILE;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 105 "fflat.l"
printf("Lex:WITH '%s' \n",yytext); return WITH;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 106 "fflat.l"
printf("Lex:YIELD '%s' \n",yytext); return YIELD;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 107 "fflat.l"
printf("Lex:IDENT '%s' \n",yytext); return IDENT;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 108 "fflat.l"
ECHO;
	YY_BREAK
#line 1394 "fflat.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 315);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 108 "fflat.l"


/*
(\n)|(\r\n)                                          printf("Lex:NEWLINE '\\n' \n"); return NEWLINE;
char \'[^\']|(\\(([bnrt\\\"\'afv])|(u([0-9a-fA-F]{4}))|(U([0-9a-fA-F]{8})|([0-9]{3}))))\'*/
/*.                                                                                                printf("Lex:codepoint \n"); return CODEPOINT; //return (int) yytext[0];*/
/*
\||->|<-|\.|\:|\(|\)|\[|\]|\[\||\|\]|\{|\}|:\?>|:\?|:>|\.\.|::|:=|;;|;|=                           return SYMBOLIC_KEYWORD;
\!|%|&|\*|\+|\-|\.|\/|<|=|>|@|\^|\||~                                                              return FIRST_OP_CHAR;
*/

