[*<*attributes*>*]
type <*ident*> =
  [*| *]<*ident*> [*of [*<*ident*> :*] <*aType*> [** [*<*ident*> :*] <*aType*> ...*]*]
  | <*ident*> [*of [*<*ident*> :*] <*aType*> [** [*<*ident*> :*] <*aType*> ...*]*]
  ...
