#!/bin/bash

mv filenamedialogue.fsx filenamedialogue.fscript
find . -name '*.fsx' | while read -r file; do
     echo $file
     i=`echo $file | sed 's/.fsx//'`
     #     mv $i.out $i.bckp
     fsharpi $i.fsx > $i.out 2>&1
done
mv filenamedialogue.fscript filenamedialogue.fsx
