#!/bin/bash

i=`echo $1 | sed 's/.fscript//'`
#     mv $i.out $i.bckp
./automatedFsharpi.exp $i.fscript > /tmp/tmp.out
cat /tmp/tmp.out | sed 's/.*H//' | sed 's///' | sed '1,9d' | sed -n -e :a -e '1,1!{P;N;D;};N;ba' > $i.out
#cat /tmp/tmp.out | sed 's/.*H//' | sed 's///' > $i.out
