#!/bin/bash
# Compile a list of files, run in mono, and store the outputfile into a file
# fsxeval2out outputfile header command

here=`pwd`
outputfilename=$1
shift
header=$1
shift

if [ -f $here/$outputfilename ]; then
    mv  $here/$outputfilename  $here/$outputfilename.bckp
fi

if [ "$header" ];then
    echo $header >>  $here/$outputfilename
fi
for i in "$@"; do
    echo "\$ $i" >> $here/$outputfilename 2>&1
    eval "$i" >> $here/$outputfilename 2>&1
done

cat $here/$outputfilename | sed -e "s#$here\/##" > /tmp/$outputfilename
mv /tmp/$outputfilename $here/$outputfilename

if [ -f $here/$outputfilename.bckp ]; then
    cmp --silent $here/$outputfilename $here/$outputfilename.bckp && rm $here/$outputfilename.bckp
fi
cat $here/$outputfilename

exit 0
