let N = 3 (*//§\label{printSquaresUnfold:N}§*)
let printSquaresUnfold n = (*//§\label{printSquaresUnfold:squares}§*)
  ( (*//§\label{printSquaresUnfold:start1}§*)
    let i = 1 (*//§\label{printSquaresUnfold:i1}§*)
    let p = i * i (*//§\label{printSquaresUnfold:p1}§*)
    printfn "%d: %d" i p (*//§\label{printSquaresUnfold:printfn1}§*)
  ) (*//§\label{printSquaresUnfold:end1}§*)
  ( (*//§\label{printSquaresUnfold:start2}§*)
    let i = 2 (*//§\label{printSquaresUnfold:i2}§*)
    let p = i * i (*//§\label{printSquaresUnfold:p2}§*)
    printfn "%d: %d" i p (*//§\label{printSquaresUnfold:printfn2}§*)
  ) (*//§\label{printSquaresUnfold:end2}§*)
  ( (*//§\label{printSquaresUnfold:start3}§*)
    let i = 3 (*//§\label{printSquaresUnfold:i3}§*)
    let p = i * i (*//§\label{printSquaresUnfold:p3}§*)
    printfn "%d: %d" i p (*//§\label{printSquaresUnfold:printfn3}§*)
  ) (*//§\label{printSquaresUnfold:end3}§*)
  
printSquaresUnfold N (*//§\label{printSquaresUnfold:call}§*)
